export default {
  "login": "brianc",
  "id": 50081,
  "node_id": "MDQ6VXNlcjUwMDgx",
  "avatar_url": "https://avatars0.githubusercontent.com/u/50081?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/brianc",
  "html_url": "https://github.com/brianc",
  "followers_url": "https://api.github.com/users/brianc/followers",
  "following_url": "https://api.github.com/users/brianc/following{/other_user}",
  "gists_url": "https://api.github.com/users/brianc/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/brianc/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/brianc/subscriptions",
  "organizations_url": "https://api.github.com/users/brianc/orgs",
  "repos_url": "https://api.github.com/users/brianc/repos",
  "events_url": "https://api.github.com/users/brianc/events{/privacy}",
  "received_events_url": "https://api.github.com/users/brianc/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Brian C",
  "company": null,
  "blog": "https://twitter.com/briancarlson",
  "location": "Austin, TX",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 152,
  "public_gists": 115,
  "followers": 776,
  "following": 32,
  "created_at": "2009-01-29T00:04:40Z",
  "updated_at": "2020-07-08T12:55:28Z"
}